version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: openisle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: openisle
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
